// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBivxofslcZkjxB39NgX_49WsMQnwChHxs',
    appId: '1:662044894018:web:68847ea96b7f8e1446dedb',
    messagingSenderId: '662044894018',
    projectId: 'mediverse-ai-86',
    authDomain: 'mediverse-ai-86.firebaseapp.com',
    databaseURL: 'https://mediverse-ai-86-default-rtdb.firebaseio.com',
    storageBucket: 'mediverse-ai-86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbSJxJ7sJNCARoQ1SuXD5OgubhpQowjs',
    appId: '1:662044894018:android:63d1800338fcdbe746dedb',
    messagingSenderId: '662044894018',
    projectId: 'mediverse-ai-86',
    databaseURL: 'https://mediverse-ai-86-default-rtdb.firebaseio.com',
    storageBucket: 'mediverse-ai-86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTgIFflUfhcnW1kZqPsbQeFurzwkXPcY',
    appId: '1:662044894018:ios:bcd6f25c7be8e52e46dedb',
    messagingSenderId: '662044894018',
    projectId: 'mediverse-ai-86',
    databaseURL: 'https://mediverse-ai-86-default-rtdb.firebaseio.com',
    storageBucket: 'mediverse-ai-86.firebasestorage.app',
    iosBundleId: 'com.example.mediverseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBivxofslcZkjxB39NgX_49WsMQnwChHxs',
    appId: '1:662044894018:web:0e65d02a03b4f95646dedb',
    messagingSenderId: '662044894018',
    projectId: 'mediverse-ai-86',
    authDomain: 'mediverse-ai-86.firebaseapp.com',
    databaseURL: 'https://mediverse-ai-86-default-rtdb.firebaseio.com',
    storageBucket: 'mediverse-ai-86.firebasestorage.app',
  );
}
